# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eccc928a6a022f6fa9ae4ff6c057e26736ad7c0fb708b7d0b97e2787de67ee8fdd5d76ad42a33315eb8ad041a9ab8ef7aa2f02d5e0a3362bd151484ed7c54040

test:
  secret_key_base: fc2714a6a105ab717b2e0db427cea4a2bfa021b09eb14098792914b9eb2847c147b4d8103c9bcbf8c7554fe8e395e4ff5bafd2811b13c40a53279b327896c09d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
